pugx_badge:
    resource: "@PUGXBadgeBundle/Controller/"
    type:     annotation
    prefix:   /

pugx_badge_packagist:
    path: /packages/{repository}
    host: "packagist.org"
    schemes:  [https]
    requirements:
      repository: "[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+"

buckler_image:
    path: /v1/{vendor}-{status}-{color}.png
    host: "b.repl.ca"
    schemes:  [http]
